### ISSUE TITLE
添加GTNH CM后进不去存档，也新建不了世界

### ISSUE THREAD

**Issue by DarkAhri** [Nxer/GTNH_Community_Mod#26]
无论是新建还是进老存档都会弹回主界面。
[fml-client-3.log](https://github.com/Nxer/GTNH_Community_Mod/files/13313709/fml-client-3.log)

**Comment by Nxer** [comment]
2.4.0需要单独更新镧系到适配版本。
使用GTCM-0.1.25还需单独更新GT

**Comment by DarkAhri** [comment]
> 2.4.0需要单独更新镧系到适配版本。
> 使用GTCM-0.1.25还需单独更新GT

原来如此，我只更新了GT，镧系最低适配版本是多少？看readme没写。

**Comment by Nxer** [comment]
> 
> 原来如此，我只更新了GT，镧系最低适配版本是多少？看readme没写。

我都甩群文件了，需要我添加钐线那个pr合并后的版本，还要适配240，你在群里就翻群文件吧

**Comment by DarkAhri** [comment]
> > 
> > 原来如此，我只更新了GT，镧系最低适配版本是多少？看readme没写。
> 
> 我都甩群文件了，需要我添加钐线那个pr合并后的版本，还要适配240，你在群里就翻群文件吧

THX
