### ISSUE TITLE
深度化学扭曲仪的900%加速似乎并没有正常工作

### ISSUE THREAD

**Issue by InsulateJustf** [Nxer/GTNH_Community_Mod#5]
![photo_2023-10-30_21-51-29](https://github.com/Nxer/GTNH_Community_Mod/assets/25749725/6c2e4101-c8d8-42ab-a286-0ed72ca5c801)
![photo_2023-10-30_21-51-35](https://github.com/Nxer/GTNH_Community_Mod/assets/25749725/e01edd8c-2ff7-46da-94b3-c0b5ad59a5f0)
化学反应釜模式下900%加速似乎并没有正常工作

**Comment by Nxer** [comment]
恐怕是我的写法有问题，大激光的加速应该是没问题的。

**Comment by Nxer** [comment]
![t1](https://github.com/Nxer/GTNH_Community_Mod/assets/43300390/f9b744ef-a126-49f6-8751-41fb2eb199dd)
![t2](https://github.com/Nxer/GTNH_Community_Mod/assets/43300390/6c5558a9-88d8-4f9a-aa17-2abb3447310b)
修了
